name: CI

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    on:
      pull_request:
        branches: [ master ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Google Services
        run: 'echo "$GOOGLE_SERVICES" > ./app/google-services.json'
        shell: bash
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
      - name: Unit Tests
        run: bash ./gradlew test --stacktrace

  apk:
    needs: test
    name: Generate APK
    runs-on: ubuntu-latest
    on:
      push:
        branches: [ master ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Google Services
        run: 'echo "$GOOGLE_SERVICES" > ./app/google-services.json'
        shell: bash
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
#      - name: Upload APK
#        uses: actions/upload-artifact@v1
#        with:
#          name: app
#          path: app/build/outputs/apk/debug/app-debug.apk
